require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SetsAndRepsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SetsAndRep. As you add validations to SetsAndRep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SetsAndRepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sets_and_reps as @sets_and_reps" do
      sets_and_rep = SetsAndRep.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sets_and_reps)).to eq([sets_and_rep])
    end
  end

  describe "GET #show" do
    it "assigns the requested sets_and_rep as @sets_and_rep" do
      sets_and_rep = SetsAndRep.create! valid_attributes
      get :show, {:id => sets_and_rep.to_param}, valid_session
      expect(assigns(:sets_and_rep)).to eq(sets_and_rep)
    end
  end

  describe "GET #new" do
    it "assigns a new sets_and_rep as @sets_and_rep" do
      get :new, {}, valid_session
      expect(assigns(:sets_and_rep)).to be_a_new(SetsAndRep)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sets_and_rep as @sets_and_rep" do
      sets_and_rep = SetsAndRep.create! valid_attributes
      get :edit, {:id => sets_and_rep.to_param}, valid_session
      expect(assigns(:sets_and_rep)).to eq(sets_and_rep)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SetsAndRep" do
        expect {
          post :create, {:sets_and_rep => valid_attributes}, valid_session
        }.to change(SetsAndRep, :count).by(1)
      end

      it "assigns a newly created sets_and_rep as @sets_and_rep" do
        post :create, {:sets_and_rep => valid_attributes}, valid_session
        expect(assigns(:sets_and_rep)).to be_a(SetsAndRep)
        expect(assigns(:sets_and_rep)).to be_persisted
      end

      it "redirects to the created sets_and_rep" do
        post :create, {:sets_and_rep => valid_attributes}, valid_session
        expect(response).to redirect_to(SetsAndRep.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sets_and_rep as @sets_and_rep" do
        post :create, {:sets_and_rep => invalid_attributes}, valid_session
        expect(assigns(:sets_and_rep)).to be_a_new(SetsAndRep)
      end

      it "re-renders the 'new' template" do
        post :create, {:sets_and_rep => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sets_and_rep" do
        sets_and_rep = SetsAndRep.create! valid_attributes
        put :update, {:id => sets_and_rep.to_param, :sets_and_rep => new_attributes}, valid_session
        sets_and_rep.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sets_and_rep as @sets_and_rep" do
        sets_and_rep = SetsAndRep.create! valid_attributes
        put :update, {:id => sets_and_rep.to_param, :sets_and_rep => valid_attributes}, valid_session
        expect(assigns(:sets_and_rep)).to eq(sets_and_rep)
      end

      it "redirects to the sets_and_rep" do
        sets_and_rep = SetsAndRep.create! valid_attributes
        put :update, {:id => sets_and_rep.to_param, :sets_and_rep => valid_attributes}, valid_session
        expect(response).to redirect_to(sets_and_rep)
      end
    end

    context "with invalid params" do
      it "assigns the sets_and_rep as @sets_and_rep" do
        sets_and_rep = SetsAndRep.create! valid_attributes
        put :update, {:id => sets_and_rep.to_param, :sets_and_rep => invalid_attributes}, valid_session
        expect(assigns(:sets_and_rep)).to eq(sets_and_rep)
      end

      it "re-renders the 'edit' template" do
        sets_and_rep = SetsAndRep.create! valid_attributes
        put :update, {:id => sets_and_rep.to_param, :sets_and_rep => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sets_and_rep" do
      sets_and_rep = SetsAndRep.create! valid_attributes
      expect {
        delete :destroy, {:id => sets_and_rep.to_param}, valid_session
      }.to change(SetsAndRep, :count).by(-1)
    end

    it "redirects to the sets_and_reps list" do
      sets_and_rep = SetsAndRep.create! valid_attributes
      delete :destroy, {:id => sets_and_rep.to_param}, valid_session
      expect(response).to redirect_to(sets_and_reps_url)
    end
  end

end
